### ISSUE TITLE
Visual design for each page

### ISSUE THREAD

**Issue by ivan-unfolds** [TechforgoodCAST/cast-website#76]

**Comment by wearecast** [comment]
How do I upload file onto here?

**Comment by andrewMacmurray** [comment]
@wearecast you can drag and drop them on desktop, will put them here

**Comment by andrewMacmurray** [comment]
![p1](https://cloud.githubusercontent.com/assets/14013616/22922965/8edcf266-f297-11e6-8140-bbc41d0fd24a.jpg)
![p2](https://cloud.githubusercontent.com/assets/14013616/22922966/8ee08e12-f297-11e6-9c2a-187e9c356fff.jpg)

**Comment by andrewMacmurray** [comment]
thanks for the designs @eghale, will be good to talk through these at the meeting tomorrow just to get an idea of how we might structure the site to fit these in

**Comment by eghale** [comment]
@andrewMacmurray @ivanmauricio Good news - Annika really likes the individual page designs (the top one) for each offering, though I might need to revise the bottom (main page) layout slightly as terms like 'design hop' won't mean anything to most users unless we've put it in the context of a wider digital transformation process/flow (which unfortunately isn't exactly linear, otherwise we could just draw arrows between each offering!) Hoping to do that over the next couple of days.

In the meantime, I've attached the Design Hop PDF, feel free to pull copy from this for the initial page mock-up. And you can find photos here: https://drive.google.com/drive/u/0/folders/0B8Wb9pceJ4GZbVNYRUJqQWNTUms
[IntroToDesignHop.pdf](https://github.com/TechforgoodCAST/cast-website/files/790249/IntroToDesignHop.pdf)

For the case studies, please just keep placeholders for now under the names Telefonica (corporate) and City Bridge Trust (funder). Shout if any questions! :)

**Comment by andrewMacmurray** [comment]
@eghale ok, we can start drafting out a page for this and see what you think

**Comment by eghale** [comment]
@andrewMacmurray @ivanmauricio New homepage wireframe is mocked up here: https://docs.google.com/document/d/1KL-nDXrAJCRjMt8yVre-CNtr9c-h9DqCtObwUe219mI/edit#

Let me know if you'd prefer it uploaded as a doc/image straight to GitHub rather than linking out - I may be committing bad practice...

**Comment by eghale** [comment]
![img_20170228_214939895](https://cloud.githubusercontent.com/assets/11066569/23435817/57714150-fe00-11e6-8c4e-50c3f3678681.jpg)
![main_page](https://cloud.githubusercontent.com/assets/12462448/23455839/0f53acf0-fe69-11e6-9e43-46bbc390156d.jpg)
![design_hops](https://cloud.githubusercontent.com/assets/12462448/23455843/11554f36-fe69-11e6-80b0-f35c3f6d69fa.jpg)

**Comment by eghale** [comment]
Sorry a couple of these are the wrong way up, thought you might be able to rotate images once uploaded. Let me know if you have trouble reading them :)

**Comment by andrewMacmurray** [comment]
@eghale thanks for these, would be good to have a chat through them face to face on Friday, are you in then?

**Comment by ivan-unfolds** [comment]
@eghale We are doing some work on these and realised that we need mobile views as well. We can discuss this tomorrow when we meet.
